### ISSUE TITLE
Minecraft estatistiken orrialdea egin

### ISSUE THREAD

**Issue by urtzai** [GameErauntsia/GameErauntsia#18]

**Comment by urtzai** [comment]
@galaipa, hemen erakutsi nahi duguna zehaztu behar dugu... Eskemaren bat egin edo dena delakoa. Ondoren, APIa prestatu behar dugu datuak erauzi eta webetik ikusgarri jartzeko. 

Nik ez nuke mysql zuzeneko konexiorik egingo ahal bada. Askoz hobe izango da aldizkako datu erauzketa bat gauzatzea eta kopia bat webguneko datu basean gordetzea. Horrela, MCko zerbitzaria gutxiago kargatuko dugu, eta konexioa erortzen bada ere, webgunean azken datuak eskuragarri izango ditugu.

Zer iruditzen?

**Comment by galaipa** [comment]
Datuak webguneko datu basean kopiatu arren, ezin ditugu mysql-tik zuzenean hartu? Hau Minecrafteko zerbitzaritik kanpo dago, beraz ez luke kargan eraginik. Zerbitzaritik API bidez hartzea konplikatugo ikusten dut, datuak ze formatutan pasa beharko genituzke?

Zerbitzariak biltzen dituen datuen zerrende [hemen](**url**) dago, hortik zer interesatzen zaigun erabaki beharko genuke.

**Comment by urtzai** [comment]
Lotura gaizki itsatsi duzu... Konpontzerik bai? Mila esker

**Comment by galaipa** [comment]
Barkatu! Hemen duzu: http://dev.bukkit.org/bukkit-plugins/lolmewnstats/

"What does this plugin log?" atalean dago zerrenda

**Comment by urtzai** [comment]
Lehentasuna kendu diot. Ikusita zer lan dauzkagu aurretik, ba hobe bestelako lanak aurrena egitea @galaipa

**Comment by urtzai** [comment]
Hari hau itxi egingo dut. Minecraft zerbitzaria ixtea pentsatu dugu eta
