### ISSUE TITLE
Paypal logoa ez da bistaratzen

### ISSUE THREAD

**Issue by ikerib** [GameErauntsia/GameErauntsia#19]
http://gamerauntsia.eus/nor-gara/

**Comment by urtzai** [comment]
URLa ez da zuzena!!

http://gamerauntsia.COM dago jarrita .EUS beharrean:

Irudia hor dago...
http://gamerauntsia.eus/media/photologue/photos/paypal_1.jpg

**Comment by ikerib** [comment]
ba nonbait .eus-etik .com-era eramaten ziguk


iKER

Urtzi Odriozola<notifications@github.com> igorleak hau idatzi zuen
(2016(e)ko otsailak 29 16:36):

**Comment by ikerib** [comment]
.eus-en ez da paypal-ekoa agertzen


iKER

iKER-<ikerib@gmail.com> igorleak hau idatzi zuen (2016(e)ko otsailak 29
16:46):

**Comment by urtzai** [comment]
Ez, arazoa hemen zegok: https://github.com/GameErauntsia/GameErauntsia/blob/master/gamerauntsia/gamerauntsia/templates/gamer/index.html#L64

HTML kodean bertan zegok .com jarrita

**Comment by ikerib** [comment]
ajjaja hori ba! nonbait egon behar zian! :D
hardcoding issues!


iKER

Urtzi Odriozola<notifications@github.com> igorleak hau idatzi zuen
(2016(e)ko otsailak 29 16:50):

**Comment by urtzai** [comment]
Widgeta copy/paste...

**Comment by ikerib** [comment]
:D


iKER

2016-02-29 16:52 GMT+01:00 Urtzi Odriozola <notifications@github.com>:
