### ISSUE TITLE
Komunitatea bereizi

### ISSUE THREAD

**Issue by urtzai** [GameErauntsia/GameErauntsia#25]
Talde motorra, youtuberrak, iritzi emaileak, besteak...

**Comment by ikerib** [comment]
youtuberrak atala garatu diat... nahikoa basikoa dek, agian hobetu liteke.

**Comment by urtzai** [comment]
Bai nire berregituraketa proposamena:

/komunitatea
/komunitatea/youtuberrak
/komunitatea/minecrafterrak
/komunitatea/idazleak
/komunitatea/guruak
/komunitatea/talde-motorra
