### ISSUE TITLE
Jakinarazpenak

### ISSUE THREAD

**Issue by ikerib** [GameErauntsia/GameErauntsia#28]
- zerbitzua publikatu
- Mugikorrerako APP-ak jakinarazpenak jasotzea aktibatu
- Profiletik aukera eman non jakinarazpenak jaso nahi dituen?

**Comment by urtzai** [comment]
Aplikazioa listo daukak?? 😍😍

Iker Ibarguren<notifications@github.com> igorleak hau idatzi zuen
(2016(e)ko maiatzak 4 17:18):

>
>    - zerbitzua publikatu
>    - Mugikorrerako APP-ak jakinarazpenak jasotzea aktibatu
>    - Profiletik aukera eman non jakinarazpenak jaso nahi dituen?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/GameErauntsia/GameErauntsia/issues/28>
>



-- 
Urtzi Odriozola Lizaso
CodeSyntax (+34) 943 821 780
http://www.codesyntax.com
Azitain Pol. 3-K
Eibar E-20600

**Comment by ikerib** [comment]
Ez ez. Zati bat agian jarri leizke publiko ta frogak iten jun






On Wed, May 4, 2016 at 8:20 AM -0700, "Urtzi Odriozola" <notifications@github.com> wrote:










Aplikazioa listo daukak?? 😍😍



Iker Ibarguren<notifications@github.com> igorleak hau idatzi zuen

(2016(e)ko maiatzak 4 17:18):



>

>    - zerbitzua publikatu

>    - Mugikorrerako APP-ak jakinarazpenak jasotzea aktibatu

>    - Profiletik aukera eman non jakinarazpenak jaso nahi dituen?

>

> —

> You are receiving this because you are subscribed to this thread.

> Reply to this email directly or view it on GitHub

> <https://github.com/GameErauntsia/GameErauntsia/issues/28>

>







-- 

Urtzi Odriozola Lizaso

CodeSyntax (+34) 943 821 780

http://www.codesyntax.com

Azitain Pol. 3-K

Eibar E-20600

**Comment by urtzai** [comment]
Aupa hi! Zati hori publikatu dezakek?
