### ISSUE TITLE
Mention sistema

### ISSUE THREAD

**Issue by ikerib** [GameErauntsia/GameErauntsia#29]
@USER erabiltzean  (Iruzkinetan, foroan) jakinarazpena bidaltzea

(https://github.com/ivirabyan/django-mentions) horrek ez dakit balioko lukeen

**Comment by urtzai** [comment]
Ikusi egin behar ea TinyMCE editorearekin bateragarria den...

**Comment by galaipa** [comment]
Oraingoz itxi
