### ISSUE TITLE
profila grabatzean errorea

### ISSUE THREAD

**Issue by ikerib** [GameErauntsia/GameErauntsia#42]
500 errorea

**Comment by urtzai** [comment]
Iepa, hau pixka bat gehiago zehazterik bai?.... MCko profila betetzean, edozein betetzean?

**Comment by ikerib** [comment]
MC


iKER

2016-06-06 10:34 GMT+02:00 Urtzi Odriozola <notifications@github.com>:

**Comment by ikerib** [comment]
eskuz sortu nian azkenean datu basean, eta haritz-ek mc zerbitzarian


iKER

2016-06-06 10:44 GMT+02:00 iKER- <ikerib@gmail.com>:

**Comment by urtzai** [comment]
@ikerib arazo honek oraindik presente jarraitzen dik?

**Comment by ikerib** [comment]
ez zekiat, nik usteyat baietz nik ez diat konpondu biñipin


iKER

2016-06-13 9:24 GMT+02:00 Urtzi Odriozola <notifications@github.com>:

**Comment by urtzai** [comment]
Hau konpondu dugula uste dut
